image: dockerhub.nie.netease.com/ux-pixels/debian-ci

stages:
  - deploy
  - notify

deploy:
  stage: deploy
  script:
    - TAG="v"$(date "+%Y%m%d_%H%M")
    - echo ${TAG}
    - docker-deploy.sh ${TAG} "uncle-y" "uncle-y" ${GROUP_PASSWORD} "feedback-server" "uncley" "feedback-server"
  only:
    - gitlab

notify_success:
  stage: notify
  script:
    - msg="项目：$CI_PROJECT_NAME\r\n任务：$CI_BUILD_REF_NAME\r\n结果：CI/CD成功\r\n查看详情：$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID"
    - curl -i -XPOST
      -H "X-Notify-AccessKey:$NOTIFY_TOKEN"
      -H 'Content-Type:application/json; charset=utf-8'
      "$NOTIFY_URL"
      -d '{"message_type":"popo","sender":"'"$NOTIFY_SENDER"'","reciever_list":["'"$NOTIFY_RECEIVER"'"],"content":"'"$msg"'"}'
  only:
    - gitlab
  when: on_success

notify_failure:
  stage: notify
  script:
    - msg="项目：$CI_PROJECT_NAME\r\n任务：$CI_BUILD_REF_NAME\r\n结果：CI/CD失败\r\n查看详情：$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID"
    - curl -i -XPOST
      -H "X-Notify-AccessKey:${NOTIFY_TOKEN}"
      -H 'Content-Type:application/json; charset=utf-8'
      "$NOTIFY_URL"
      -d '{"message_type":"popo","sender":"'"$NOTIFY_SENDER"'","reciever_list":["'"$NOTIFY_RECEIVER"'"],"content":"'"$msg"'"}'
  only:
    - gitlab
  when: on_failure
